-- v2.3: Reliable config delivery — add config_deliveries table

CREATE TABLE IF NOT EXISTS `config_deliveries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `msg_id` VARCHAR(64) NOT NULL,
  `trace_id` VARCHAR(64) NOT NULL DEFAULT '',
  `device_code` VARCHAR(64) NOT NULL,
  `config_type` VARCHAR(64) NOT NULL,
  `action` VARCHAR(16) NOT NULL,
  `entity_id` BIGINT UNSIGNED NOT NULL,
  `entity_rev` BIGINT UNSIGNED NOT NULL,
  `schema_version` INT NOT NULL DEFAULT 1,
  `issued_at_ms` BIGINT UNSIGNED NOT NULL,
  `ttl_sec` INT NOT NULL DEFAULT 600,
  `require_ack` TINYINT(1) NOT NULL DEFAULT 1,
  `request_payload` JSON NOT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  `retry_count` INT NOT NULL DEFAULT 0,
  `next_retry_at` DATETIME(3) DEFAULT NULL,
  `sent_at` DATETIME(3) DEFAULT NULL,
  `acked_at` DATETIME(3) DEFAULT NULL,
  `last_error_code` VARCHAR(64) NOT NULL DEFAULT '',
  `last_error_message` VARCHAR(255) NOT NULL DEFAULT '',
  `ack_payload` JSON DEFAULT NULL,
  `applied_hash` VARCHAR(128) NOT NULL DEFAULT '',
  `device_fw_version` VARCHAR(64) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_config_deliveries_msg_id` (`msg_id`),
  UNIQUE KEY `uk_config_deliveries_entity_rev` (`device_code`, `config_type`, `entity_id`, `entity_rev`),
  KEY `idx_config_deliveries_status_retry` (`status`, `next_retry_at`),
  KEY `idx_config_deliveries_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
